### ISSUE TITLE
pip install broken v1.1.1

### ISSUE THREAD

**Issue by gbouras13** [linsalrob/sphae#20]
Just tried to install from pip in a separate conda env:

```
mamba create -n sphae pip
conda activate sphae
pip install sphae

(sphae) $ sphae -h
Traceback (most recent call last):
  File "~/myconda/envs/sphae/bin/sphae", line 5, in <module>
    from sphae.__main__ import main
ModuleNotFoundError: No module named 'sphae'

```

Install from source works fine.

George

**Comment by gbouras13** [comment]
also `sphere install` took like 15 minutes, Zenodo backend improvements have sped up Pharokka and Phynteny DB downloads :)

**Comment by npbhavya** [comment]
> Just tried to install from pip in a separate conda env:
> 
> ```
> mamba create -n sphae pip
> conda activate sphae
> pip install sphae
> 
> (sphae) $ sphae -h
> Traceback (most recent call last):
>   File "~/myconda/envs/sphae/bin/sphae", line 5, in <module>
>     from sphae.__main__ import main
> ModuleNotFoundError: No module named 'sphae'
> ```
> 
> Install from source works fine.
> 
> George

Thanks for testing the pip installation; I will look into this error with the next release. 
I have been adding other small changes as I come across small issues or ideas to make the workflow smoother. I will push another version to pypi later with all these updates. Unfortunately, this means sticking to source install for a bit longer.

**Comment by npbhavya** [comment]
Resolved now
