### ISSUE TITLE
Building the singularity container produces errors

### ISSUE THREAD

**Issue by mattheww95** [linsalrob/sphae#38]
Recently when running the command to pull the docker container that contains the databases (`singularity pull docker://npbhavya/sphae:latest`) I suddenly received a large number of errors after downloading the container downloaded and it was generating signatures.

A large number of fatal error were listed afterwards (see relevant picture), but sadly I could not get a screenshot with more information as my computer became unusable and required re-booting.
![image](https://github.com/user-attachments/assets/043767ef-9086-42df-9524-a5a90b136c84)

A collegue of mine has had similar issues while trying to download the container as well.

My computer specifiications are as follows:

Apptainer version (singularity): 1.2.2
OS: Ubuntu 22.04.3 LTS on Windows 10 x86_64
Kernel: 5.15.153.1-microsoft-standard-WSL2
Shell: bash 5.1.16
CPU: Intel i7-8665U (6) @ 2.112GHz
GPU: aa46:00:00.0 Microsoft Corporation Device 008e
Memory: 336MiB / 24038MiB

**Comment by npbhavya** [comment]
Hi, 

I haven't testes the docker image on WSL, its working on mac and RedHat, so let me give that a try and get back to you. Meanwhile, sphae is available to download as both pip and conda packages as well. 

Thank you, 
Bhavya

**Comment by mattheww95** [comment]
Thank you so much! The error only occured when I was converting the docker container to a singularity image, their may have been some issues on my computer with memory usage at the  time, however my collegue had similar issues.

We are proceeding with using a conda installation for now but I just wanted to let you know about the issue we encoutered in case any one else does!

Please feel free to close the issue if you cannot re-create it, thank you for your time!

**Comment by npbhavya** [comment]
I wasn’t able to replicate the error when converting the Docker image to a Singularity image, even after re-running the command on both RedHat and macOS. Did your colleague run into this issue on Windows or another OS? 

I hope there were no issues with the Conda installation

**Comment by mattheww95** [comment]
The conda installation went well and we are able to run Sphae locally :)

My collegue was trying to perform the container conversion on CentOS 7 but I do not have an output of his error messages. As the conda install is working and you are unable to re-create the issue I will close the issue with this comment.

Thank you so much for you help and patience trying to recreate the issue!
